name: Test Emscripten/Pyodide build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # daily scheduled build at 4am
  schedule:
      - cron: "0 4 * * *"

jobs:
  build-wasm-emscripten:
    runs-on: ubuntu-latest
    env:
      PYODIDE_VERSION: '0.22.0a3'
      PYODIDE_JS_VERSION: '0.22.0-alpha.3'
      PYTHON_VERSION: '3.10.7'
      NODE_VERSION: 18
      EMSCRIPTEN_VERSION: 3.1.24
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{ env.EMSCRIPTEN_VERSION }}
          actions-cache-folder: emsdk-cache

      - name: Install pyodide-build
        run: pip install pyodide-build==$PYODIDE_VERSION

      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: install Pyodide
        run: |
          npm install "pyodide@$PYODIDE_JS_VERSION"
      - name: install debug build
        run: |
          wget http://pyodide-cache.s3-website-us-east-1.amazonaws.com/scratch/pyodide-scipy-debug.tar.xz
          tar pyodide-scipy-debug.tar.xz
          cp dist/* node_modules/pyodide

      - name: Test
        run: |
          python run-tests-by-module.py
